import type { Metadata } from "next";
import { Tomorrow } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const tomorrow = Tomorrow({
  weight: "400",
  variable: "--font-tomorrow",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Surrey CompSoc",
    template: "%s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tomorrow.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
